set -g mouse on
set -g default-terminal "tmux-256color"
set -sg escape-time 10

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind | split-window -h
bind - split-window -v

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection-and-cancel

bind r source-file ~/.tmux.conf \; display "reloaded"

set -g status-interval 5
set -g status-left-length 20
set -g status-right-length 40
set -g status-left "#[fg=#565f89] #S "
set -g status-right "#[fg=#565f89] %H:%M "
set -g status-style "bg=#1a1b26,fg=#565f89"
set -g message-style "bg=#1a1b26,fg=#7dcfff"
set -g pane-active-border-style "fg=#7dcfff"
set -g pane-border-style "fg=#292e42"
