all:
  children:
    debian_servers:
      hosts:
        osiris:
          ansible_host: 34.93.223.168
          ansible_user: deploy
        pendle:
          ansible_host: PENDLE_IP_HERE
          ansible_user: deploy
        implied:
          ansible_host: 35.200.174.138
          ansible_user: deploy
    new_servers:
      hosts: {}
