color_theme = "tokyo-night"
theme_background = true
truecolor = true
vim_keys = true
proc_sorting = "memory"
proc_tree = true
proc_per_core = true
proc_mem_bytes = true
proc_cpu_graphs = true
proc_left = false
update_ms = 1500
shown_boxes = "cpu mem net proc"
show_cpu_watts = true
check_temp = true
temp_scale = "celsius"
show_cpu_freq = true
clock_format = "%X"
mem_graphs = true
show_swap = true
swap_disk = true
show_disks = true
only_physical = true
use_fstab = true
show_io_stat = true
net_auto = true
net_sync = true
show_battery = true
show_battery_watts = true
log_level = "WARNING"
save_config_on_exit = true
