---
- name: Set default incoming policy to deny
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Set default outgoing policy to allow
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: Allow allowed TCP ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ ufw_allowed_tcp_ports }}"

- name: Enable UFW
  community.general.ufw:
    state: enabled

- name: Enable UFW logging
  community.general.ufw:
    logging: 'medium'
