---
- name: Configure SSH hardening
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
    validate: 'sshd -t -f %s'
  notify: restart sshd

- name: Ensure fail2ban is enabled and running
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: started
