---
collections:
  - name: community.general
    source: https://galaxy.ansible.com
  - name: ansible.posix
    source: https://galaxy.ansible.com
  - name: google.cloud
    source: https://galaxy.ansible.com
  - name: devsec.hardening
    source: https://galaxy.ansible.com

roles:
  - name: geerlingguy.docker
    src: https://github.com/geerlingguy/ansible-role-docker
  - name: geerlingguy.firewall
    src: https://github.com/geerlingguy/ansible-role-firewall
